### ISSUE TITLE
Ryzen Integrated Graphics Compatibility

### ISSUE THREAD

**Issue by max-aider** [kolgushev/Pixel-Perfect-B#1]
I tried to enable the shader while in world, but it didn't work and the "(fallback)" thing appeared. Then I tried to change the settings of the shader a few times, but it crashed. Here's the log with all the details: https://mclo.gs/rdwvnKI

**Comment by kolgushev** [comment]
Thanks for submitting a bug report.
Do you still have the settings you used when the shader crashed? You can find them as a text file with the same name as the shader in your shaders folder. Also, which version you were using? I think you renamed the file so I can't tell which version it was just from the logs.

**Comment by kolgushev** [comment]
It would also help to say what graphics card you have, if you know that.

**Comment by max-aider** [comment]
I'm on AMD Ryzen 5 5500U with Radeon Graphics. Shader version 1.3.1. Here's the error given by Iris:
```
deferred.fsh: deferred.fsh: ERROR: 0:180: 'constructor' : array constructor needs one argument per array element 
ERROR: 0:180: '=' :  cannot convert from ' const float' to ' temp 4-element array of float'
ERROR: 0:180: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```

**Comment by kolgushev** [comment]
The issue should be fixed in Pixel Perfect 1.3.2, which has just gone live on Modrinth and CurseForge. Unfortunately I didn't have an AMD graphics card on hand, so I had to test the issue on an Intel iGPU. Please reply with whether this fixed it for you so I know if I can close the issue.

**Comment by max-aider** [comment]
```
sky_basic.fsh: sky_basic.fsh: ERROR: 0:174: 'clamp' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 0:174: 'assign' :  cannot convert from ' const double' to ' temp 3-component vector of float'
ERROR: 0:174: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```

**Comment by kolgushev** [comment]
Try using this shaderpack, hopefully it fixes the issue. Not releasing it yet since I'm not sure it fixes the issue.

[Pixel-Perfect-Integrated-Graphics-Patch.zip](https://github.com/kolgushev/Pixel-Perfect-B/files/11962437/Pixel-Perfect-Integrated-Graphics-Patch.zip)

**Comment by max-aider** [comment]
Same error

**Comment by kolgushev** [comment]
Could you please load the shader in Iris and then attach `.minecraft>patched_shaders` as a zip file? That would help me a lot since that contains the file that's mentioned in the file and changes depending on which device the shader is loaded on.

Thanks for being so helpful, by the way

**Comment by max-aider** [comment]
[patched_shaders.zip](https://github.com/kolgushev/Pixel-Perfect-B/files/11968770/patched_shaders.zip)

**Comment by kolgushev** [comment]
Are you absolutely sure it's the exact same error? Nothing in the text has changed, not even the numbers?

**Comment by kolgushev** [comment]
Are you absolutely sure you got the exact same error as last time, including the line numbers?

**Comment by max-aider** [comment]
Yes, if I enable your file with the Iris config option `enableDebugOptions=false`. If I set that to true (in order for the folder, that you asked me to zip, to appear), turns out the error is different:
```
net.coderbot.iris.gl.shader.ShaderCompileException: sky_basic.fsh: sky_basic.fsh: ERROR: 0:285: 'clamp' : ambiguous function signature match: multiple signatures match under implicit type conversion 
ERROR: 0:285: 'assign' :  cannot convert from ' const double' to ' temp 3-component vector of float'
ERROR: 0:285: '' : compilation terminated 
ERROR: 3 compilation errors.  No code generated.
```
I didn't see that at first because Iris didn't send the usual error message in the chat, so I didn't bother to check

**Comment by kolgushev** [comment]
[Pixel-Perfect-Patch-2.zip](https://github.com/kolgushev/Pixel-Perfect-B/files/11971318/Pixel-Perfect-Patch-2.zip)
Does this change your error at all?

**Comment by max-aider** [comment]
It works! All three modes. Are there any specific settings that I should test?

**Comment by kolgushev** [comment]
Not really, but please do submit another issue if you do end up finding a setting that doesn't work - thanks for all your help, and I'll be posting the patch on Modrinth and CurseForge soon™.
