### ISSUE TITLE
lines.vsh: lines.vsh: 0:1(10): error: the compatibility profile is not supported

### ISSUE THREAD

**Issue by i-can-not-program** [kolgushev/Pixel-Perfect-B#3]
**Describe the bug**
The shader doesnt load and gives this error:
`lines.vsh: lines.vsh: 0:1(10): error: the compatibility profile is not supported`

**To Reproduce**
1. Have amd gpu
2. Use nixos and hyprland (wlroots based wayland compositor)
3. get minecraft 1.20.1 with fabric sodium and iris
4. use shader and `The shaderpack failed to load! Please report the error to the shader developer. Copy Info`

**Expected behavior**
I expect the shaderpack to load

**Screenshots**

**Desktop (please complete the following information):**
 - Loader and loader version [e.g. Optifine HD U H9, Iris 1.6.2] Iris 1.6.4
 - Minecraft version [e.g. Minecraft 1.19.4] 1.20.1
 - Graphics Card [e.g. RTX 3050 Ti for Laptop, Radeon RX 6800XT] Radeon RX 6600
 - OS: [e.g. Windows, Linux, MacOS] Linux (NixOS)

**Additional context**

**Comment by kolgushev** [comment]
Try using these patched shaders:
[Pixel-Perfect-Latest.zip](https://github.com/kolgushev/Pixel-Perfect-B/files/12236713/Pixel-Perfect-Latest.zip)

If it still doesn't work, go into the shader select menu, press `Ctrl+D` to enable debug mode, then reload the shaders (The `R` key by default). In addition to the error message being more detailed, a `patched_shaders` folder should have appeared in your `.minecraft` folder (which should be placed in your home folder - if you don't see it, try pressing `Ctrl+H` in your file browser). If you could zip that folder and send it here, that would help a ton with my debugging.
