### ISSUE TITLE
Deferred0 texture2D namespace error

### ISSUE THREAD

**Issue by Abbyb0o0** [kolgushev/Pixel-Perfect-B#4]
deferred.fsh: deferred.fsh: ERROR: 0:112: Invalid call of undeclared identifier 'texture2D'

**Comment by kolgushev** [comment]
Does this fix your issue?
[Pixel-Perfect-Patched.zip](https://github.com/kolgushev/Pixel-Perfect-B/files/12501980/Pixel-Perfect-Patched.zip)

If not, it would be helpful for me to know which version of Iris/Optifine you're running, your GPU model, your version of Pixel Perfect, etc.

**Comment by kolgushev** [comment]
Please reply with whether the bug fixed your issue. If you don't, I'll assume the bug fixed and close the issue.
