### ISSUE TITLE
Distant Horizons Support

### ISSUE THREAD

**Issue by MrZeroSkill** [kolgushev/Pixel-Perfect-B#6]
**Is your feature request related to a problem? Please describe.**
Nope!

**Describe the solution you'd like**
Support for Distant Horizons, the LOD mod.

**Describe alternatives you've considered**
Turning my render distance to 100, but that KILLS my VRAM.

**Additional context**
I just think this'd be a cool feature. I really love the shaderpack.

**Comment by kolgushev** [comment]
The latest version of the shader (1.5) should be compatible with Distant Horizons already, so long as you have Iris+Indium... Is it crashing/not rendering/something else?
Or is the issue that turning your **Distant Horizons** render distance up kills VRAM?

**Comment by kolgushev** [comment]
Also, what version of Minecraft/Iris are you using?

**Comment by MrZeroSkill** [comment]
I was seeing errors initially, but oddly on trying again they seemed to have gone away now. Sorry! from that + the fact that usually DH support is a heavily advertised feature I had assumed there was no support lol.

**Comment by kolgushev** [comment]
👍
