### ISSUE TITLE
Selection Outline broken on 1.21

### ISSUE THREAD

**Issue by pbl0** [kolgushev/Pixel-Perfect-B#7]
**Describe the bug**
Both "Show Entire Selection Outline" and "Selection Outline Color" appears to be broken on Minecraft 1.21.
The default outline is also barely visible. The only color that seems to do something is the Negative that shows a thin yellow outline. I've also tested it on 1.20.6 and it works fine.

**To Reproduce**
1. Install a Minecraft instance on 1.21 with Fabric Loader 0.16.0, Fabric API 0.102.0, Sodium 0.5.11, Iris Shaders 1.7.3, Indium 1.0.34 and Pixel Perfect 1.5.1.
2. Enable Shaders and select Pixel Perfect 1.5.1.
3. Change either "Show Entire Selection Outline" or "Selection Outline Color". 
4. Nothing happens.

**Expected behavior**
Expect to see the selection outline to change colors and/or show the entire selection outline.

**Screenshots**
![image](https://github.com/user-attachments/assets/ca062f8f-5320-4d33-8d79-caccc6e2e48f)

![image](https://github.com/user-attachments/assets/4bad8a2c-3efb-4ae5-b9dd-bd593dfe33c5)

**Comment by kolgushev** [comment]
On it

**Comment by kolgushev** [comment]
Try this pack, and tell me if that fixed it please:
[Pixel-Perfect-Latest-Beta-1.zip](https://github.com/user-attachments/files/16553761/Pixel-Perfect-Latest-Beta-1.zip)

![image](https://github.com/user-attachments/assets/fcd72f29-7030-4372-a61e-e781e8970a03)

**Comment by pbl0** [comment]
Yeah, that fixed it, it now works as expected. Thanks! :)

**Comment by kolgushev** [comment]
👍

I've also fixed some more bugs in 1.5.2 which I'll publish in a few minutes, so you can use that instead of the beta pack when it's out.

**Comment by kolgushev** [comment]
Strike that, there's some pretty major issues on Optifine, but you can still get the (broken on Optifine) release [here](https://github.com/kolgushev/Pixel-Perfect-B/releases/tag/v1.5.2).
